from typing import Any,Literal
from pydantic import BaseModel,Field
class LLMMessage(BaseModel): role:Literal['system','user','assistant']; content:str
class LLMUsage(BaseModel): prompt_tokens:int|None=None; completion_tokens:int|None=None; total_tokens:int|None=None
class LLMOptions(BaseModel): temperature:float|None=None; max_tokens:int|None=None; timeout:float|None=None; metadata:dict[str,Any]=Field(default_factory=dict)
class LLMResponse(BaseModel):
    content:str; provider:str; model:str; finish_reason:str|None=None; usage:LLMUsage=Field(default_factory=LLMUsage); latency_ms:int=0; request_id:str|None=None; metadata:dict[str,Any]=Field(default_factory=dict)
class ProcurementContext(BaseModel):
    intent:str='GENERAL_PROCUREMENT_DIALOGUE'; is_procurement:bool=True; subject:str=''; category:str=''; counterparty_type:str=''; amount:float|None=None; currency:str='RUB'; goods_services_works:str=''; procurement_object_type:str=''; requires_transfer_of_goods:bool|None=None; requires_service_activity:bool|None=None; requires_tangible_work_result:bool|None=None; requires_agent_actions:bool|None=None; agent_acts_in_principal_interest:bool|None=None; materials_purchase_required:bool|None=None; acceptance_result_type:str=''; delivery_required:bool|None=None; delivery_location:str=''; installation_required:bool|None=None; support_required:bool|None=None; licensing_required:bool|None=None; new_software_development:bool|None=None; intellectual_property_related:bool|None=None; personal_data_related:bool|None=None; advance_payment:bool|None=None; term:str=''; restrictions:list[str]=Field(default_factory=list); exceptions:list[str]=Field(default_factory=list); source_confidence:float|None=None; has_technical_specification:bool=False; missing_fields:list[str]=Field(default_factory=list); resolved_fields:list[str]=Field(default_factory=list); last_clarification_fields:list[str]=Field(default_factory=list); last_clarification_question:str=''; clarification_repeat_count:int=0; suggested_options:list[str]=Field(default_factory=list); ordinary_supply_confirmed:bool=False
class RequirementsExtractionResult(BaseModel):
    intent:str='GENERAL_PROCUREMENT_DIALOGUE'; is_procurement:bool=True; category:str=''; subject:str=''; counterparty_type:str=''; amount:float|None=None; currency:str='RUB'; procurement_object_type:str=''; requires_transfer_of_goods:bool|None=None; requires_service_activity:bool|None=None; requires_tangible_work_result:bool|None=None; requires_agent_actions:bool|None=None; agent_acts_in_principal_interest:bool|None=None; materials_purchase_required:bool|None=None; acceptance_result_type:str=''; delivery_required:bool|None=None; delivery_location:str=''; installation_required:bool|None=None; support_required:bool|None=None; licensing_required:bool|None=None; new_software_development:bool|None=None; intellectual_property_related:bool|None=None; personal_data_related:bool|None=None; advance_payment:bool|None=None; term:str=''; restrictions:list[str]=Field(default_factory=list); exceptions:list[str]=Field(default_factory=list); purpose:str=''; scope:str=''; functional_requirements:str=''; nonfunctional_requirements:str=''; deadline:str=''; acceptance_criteria:str=''; other_conditions:str=''; items:list[dict[str,Any]]=Field(default_factory=list); item_updates:list[dict[str,Any]]=Field(default_factory=list); common_requirements:list[str]=Field(default_factory=list); blocking_requirements:list[str]=Field(default_factory=list); remove_blocking_requirements:list[str]=Field(default_factory=list); additional_conditions:list[str]=Field(default_factory=list); remove_phrases:list[str]=Field(default_factory=list); resolved_fields:list[str]=Field(default_factory=list); confidence:float=1
class SpecificationAnalysisResult(BaseModel):
    context:ProcurementContext; specification:RequirementsExtractionResult; summary:str
class DialogueState(BaseModel):
    case_id:str; intent:str; procurement_category:str; specification_fields:dict[str,Any]; missing_fields:list[str]; clarification_questions:list[str]; confidence:float=1; last_operation:str=''; status:str=''
